Monitoring 1
Otus-DevOps-2023-01/coolerWhite_microservices pull request #12
Opened 2023-06-18 09:25 UTC by coolerWhite

# Выполнено ДЗ № 17

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-06-18 09:27 UTC, coolerWhite commented
Добрый день
Не понимаю причины ошибки 
HTTP GET on http://post:5000/healthcheck body

2023-06-25 13:28 UTC, mrgreyves requested changes
Здравствуйте!)
/bin/sh -c apk -y install gcc mono-mcs &&     apk -y install musl-dev
Это точно нужно в сборке?)

2023-06-26 13:46 UTC, coolerWhite commented
здравствуйте, подправил но присутствует ошибка с ДЗ Докер-3. как я понимаю она будет продолжаться?

2023-07-11 15:31 UTC, mrgreyves approved these changes
Здравствуйте!)
Да, вполне проблемы с резолвол днс записей могут быть

2023-07-11 16:41 UTC, merged